cores: 28
latency-wait: 30
keep-going: True
rerun-incomplete: True
restart-times: 2
max-status-checks-per-second: 0.001
use-conda: True
conda-frontend: conda
nolock: False
configfile: config/config.yaml

