- name: Download miniconda.
  ansible.builtin.get_url:
    url: 'https://repo.anaconda.com/miniconda/Miniconda3-{{ miniconda_version }}-Linux-x86_64.sh'
    dest: /tmp/miniconda3.sh
    mode: 0744
- name: Install miniconda.
  ansible.builtin.command: >
    /tmp/miniconda3.sh -b -f -p /home/ubuntu/miniconda3
  args:
    creates: /home/ubuntu/miniconda3/bin/conda
- name: Add Miniconda to PATH environment variable.
  ansible.builtin.lineinfile:
    path: /home/ubuntu/.bashrc
    line: 'export PATH=/home/ubuntu/miniconda3/bin:$PATH'
    create: yes
    state: present
- name: Download micromamba.
  ansible.builtin.get_url:
    url: 'https://micro.mamba.pm/install.sh'
    dest: /tmp/micromamba.sh
    mode: 0744
- name: Install micromamba.
  ansible.builtin.command: >
    /tmp/micromamba.sh
  args:
    creates: "{{ home_path }}/.local/bin/micromamba"
- name: Install apt packages.
  become: true
  ansible.builtin.apt:
    update_cache: yes
    pkg: 
      - build-essential
      - cmake
      - libgsl-dev
      - libhts-dev
      - libjemalloc-dev
      - libz-dev
      - libzstd-dev
      - python3-distutils 
      - python3-dev
      - pkg-config
- name: Download snakemake.
  ansible.builtin.get_url:
    url: 'https://github.com/snakemake/snakemake/archive/refs/tags/v{{ snakemake_version }}.tar.gz'
    dest: /tmp/snakemake_{{ snakemake_version }}.tar.gz
    owner: ubuntu
    mode: 0755
- name: Unzip snakemake.
  ansible.builtin.unarchive:
    src: /tmp/snakemake_{{ snakemake_version }}.tar.gz
    dest: '{{ home_path }}/'
    remote_src: true
- name: Install snakemake.
  pip:
    name: '{{ home_path }}/snakemake-{{ snakemake_version }}/'
    executable: '{{ home_path }}/miniconda3/bin/pip3'
    state: present
- name: Copy snakemake to path.
  become: true
  ansible.builtin.copy:
    src: '{{ home_path }}/miniconda3/bin/snakemake'
    dest: /usr/local/bin/snakemake 
    remote_src: true
    owner: ubuntu
    group: ubuntu
    mode: '0755'
- name: Add conda init bash to .bashrc
  ansible.builtin.lineinfile:
    path: '{{ home_path }}/.bashrc'
    line: "conda init bash"
    state: present
    create: yes
  notify:
    - reload bash
